-- AlterTable
ALTER TABLE "concert_memories" ADD COLUMN     "best_live_song" TEXT,
ADD COLUMN     "crowd_rating" INTEGER,
ADD COLUMN     "energy_after" INTEGER,
ADD COLUMN     "entrance_rating" INTEGER,
ADD COLUMN     "experience_tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "km_traveled" INTEGER,
ADD COLUMN     "main_act_rating" INTEGER,
ADD COLUMN     "mood_rating" INTEGER,
ADD COLUMN     "overall_rating" INTEGER,
ADD COLUMN     "setlist_rating" INTEGER,
ADD COLUMN     "song_missed" TEXT,
ADD COLUMN     "stage_show_rating" INTEGER,
ADD COLUMN     "support" TEXT,
ADD COLUMN     "support_act_rating" INTEGER,
ADD COLUMN     "ticket_image_url" TEXT,
ADD COLUMN     "tour" TEXT,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "venue" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL;
